services:
  - type: web
    name: rnlp-proxy
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: ADMIN_KEY
        generateValue: true
      - key: ENVIRONMENT
        value: production
      - key: PUBLIC_API_BASE
        value: https://api.initial3development.com
      - key: SERVICE_VERSION
        value: 3.5.0
      - key: DATABASE_URL
        sync: false
      - key: WALKSCORE_API_KEY
        sync: false
      - key: NREL_API_KEY
        value: DEMO_KEY
      - key: BLS_API_KEY
        sync: false
